/*
Navicat MySQL Data Transfer

Source Server         : localhost
Source Server Version : 50173
Source Host           : localhost:3306
Source Database       : shanghua

Target Server Type    : MYSQL
Target Server Version : 50173
File Encoding         : 65001

Date: 2016-12-19 15:39:19
*/

SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for producten
-- ----------------------------
DROP TABLE IF EXISTS `producten`;
CREATE TABLE `producten` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `title` varchar(255) DEFAULT NULL,
  `content` varchar(2000) DEFAULT NULL,
  `thumb` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=65 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of producten
-- ----------------------------
INSERT INTO `producten` VALUES ('1', 'Design software', 'Show underground space information technology    \r\nThe pipe gallery performance analysis', '../Public/uploads/2016-12-17/585538c06d5e1.png');
INSERT INTO `producten` VALUES ('2', 'Operational system', 'Based on the construction of informatization\r\n  Promote the utility tunnel construction', '../Public/uploads/2016-12-17/5855390f5853f.png');
INSERT INTO `producten` VALUES ('3', 'The green building', 'Integrated building performance simulation analysis\r\n  A high degree of unity design and analysis', '../Public/uploads/2016-12-17/5855395b36cbb.png');
INSERT INTO `producten` VALUES ('4', 'Design assistantDWHelp', 'Based on the ACE industry designer perspective\r\nImprove the design efficiency', '../Public/uploads/2016-12-17/585539861a3a0.png');
INSERT INTO `producten` VALUES ('5', 'PDMS Synthetic', 'Based on the affiliated with EXCEL VBA language\r\n      Focus on the 3 d pipeline design', '../Public/uploads/2016-12-19/58578e74ea207.png');
INSERT INTO `producten` VALUES ('6', 'PDMS wind', 'Based on BIM off-line navigation platform development\r\n        In accordance with domestic design', '../Public/uploads/2016-12-17/585539de56a74.png');
INSERT INTO `producten` VALUES ('7', 'Process design software', 'Provide you with all aspects\r\n   Process design tools', '../Public/uploads/2016-12-17/58553a0ce7eca.png');
INSERT INTO `producten` VALUES ('8', 'GREEN CONSTRUCTION SIMULATION ANALYSIS', '', '../Public/uploads/2016-12-17/58554a96b8429.jpg');
INSERT INTO `producten` VALUES ('9', 'SOFTWARE INTRODUCTION', 'Analysis of green building simulation software (hereinafter referred to as IES) analysis software analysis software analysis software is simulated by the integrated green building performance developed by the British IES simulated by the integrated green building performance developed by the British IES simulated by the integrated green building performance developed by the British IES.', '../Public/uploads/2016-12-17/58554b18edeb8.png');
INSERT INTO `producten` VALUES ('10', 'THE MAIN FUNCTION', '（1）To establish a three-dimensional information architecture model,such as Revit or Sketchup, etc..\r\n（2）ApacheLoad according to ASHRAE (American heating, refrigeration and air conditioning engineering is the Association) standards for the calculation of hot and cold load.\r\n（3）Calculate the annual energy consumption, CO2 emissions, indoor air quality and so on, calculate the annual energy consumption of air conditioning system.\r\n（4） Simulation of natural ventilation of buildings, the results for the calculation of energy consumption.\r\n（5）Calculate the natural lighting inside and outside the building, you can show the results of the calculation directly.\r\n（6）Calculate the lighting, artificial lighting inside and outside the building, you can show the calculation directly\r\n（7）Calculate the construction of the solar block coefficient, and can be used to calculate the shielding coefficient of thermal simulation, you can dynamically display the day of the sun changes.\r\n（8）Calculating the time required for all personnel to leave the building in a dynamic simulation\r\n（9）By means of finite volume method, the internal and external 3D wind environment is calculated, the temperature field and flow field are simulated, andtemperature contour and thermal comfort.\r\n', '../Public/uploads/2016-12-17/58554be41158e.png');
INSERT INTO `producten` VALUES ('11', 'Building', '', '../Public/uploads/2016-12-17/58554c639cf7d.png');
INSERT INTO `producten` VALUES ('12', 'The bird\'s nest', '', '../Public/uploads/2016-12-17/58554c87bfc81.png');
INSERT INTO `producten` VALUES ('13', 'The Water Cube', '', '../Public/uploads/2016-12-17/58554c99a93be.png');
INSERT INTO `producten` VALUES ('14', 'GENENAL INTRODUCTION', 'IES is the world\'s well-known design units and engineering consulting units used, such as Arup (), WSP (Ke Jin), Atkins (Atkins), PB (Bai Cheng), and so on. These well-known design company or engineering company wide use of IES &lt;VE&gt; as they participate in the competition in the domestic project tools, and well-known projects are the bird\'s nest, water cube, Pudong International Airport, Beijing International Airport, Nokia Plaza, etc.. &lt;VE&gt; IES to the design of the square is not only a beautiful three-dimensional model,the real design of a high degree of unity of emotional and rational analysis.', '../Public/uploads/2016-12-17/58554ccc032b6.png');
INSERT INTO `producten` VALUES ('15', 'DESIGN ASSISTANT DWHELP', '', '../Public/uploads/2016-12-17/58554de1d167f.png');
INSERT INTO `producten` VALUES ('16', 'GENERAL INTRODUCTION', 'Design assistant DWGHelp (or name: drawing assistant DWGHelp) is a specialized research and development of professional tools for digital drawing, main function modules including: drawings protection, security, drawing drawings signature, electronic signature, intelligent printing watermark, drawings, etc. The units can be completed quickly, such as: stamp figure sign, personal chop sign, qr code and other intelligent drawing implant. Second, DWGHelp research and development of intelligent based on ACE industry designer to create, drawing tools, tools layer, drawing ratio and drawing notation, viewport tools such as single point of function module to improve the design process, collaborative (collaboration), communication and figure whose work efficiency.\r\n  DWGHelp AutoCAD platform with the survey and design unit is widely used and highly integrated CAD secondary development software, can automatically realize batch, automatic signature and signed the drawings of the following characteristics: do not edit, on the basis of meet the digital drawing, also protect the enterprise\'s intellectual property rights, building design enterprise\'s good helper.\r\n      ', '../Public/uploads/2016-12-17/58554e172c0fe.jpg');
INSERT INTO `producten` VALUES ('17', 'SOFTWARE MAIN INTERFACE', 'Design assistant main functions are listed on the menu screen, and the main menu, main menu and the screen menu. Main interface of the software are as follows:', '../Public/uploads/2016-12-17/58554e875f087.png');
INSERT INTO `producten` VALUES ('18', 'SOFTWARE FUNCTIONAL CHARACTERISTICS', 'Intelligent identification enterprise standard drawing frame, realizing the rapid digital figure out;\r\nProvide enterprise to stamp, all kinds of drawings to sign management functions, convenient and flexible application;\r\nOutgoing DWG drawings of security protection, the watermark encryption function;\r\nDigital signature drawings of security protection, protection level according to drawings important level Settings; \r\n when the printing signature knowledge of enterprise intellectual property rights (ipr) protection drawing features.', '../Public/uploads/2016-12-17/58554ed4592ce.jpg');
INSERT INTO `producten` VALUES ('19', 'PDMS COMPOSITE MATERIAL AUTOMATIC TYPESETTING', '', '../Public/uploads/2016-12-17/58554fbd82cfd.jpg');
INSERT INTO `producten` VALUES ('20', 'PRODUCT INTRODUCTION', 'PDMS design software is a factory, the main function is the 3 d pipeline design.', '../Public/uploads/2016-12-17/58554fdd8bc63.png');
INSERT INTO `producten` VALUES ('21', 'GENERAL INTRODUCTION', 'PDMS design software is a factory, the main function is the 3 d pipeline design. Can automatically generate the equipment layout, piping layout, ISO figure, composite material table, etc. Make use of the automatic generation of ISO figure is more perfect, generally have generated CAD equipment layout, piping layout needs to modify a moderate amount of composite materials, table is very chaotic, need manual layout (period error prone), due to various reasons after typesetting often need to modify the model to the material, recomposition, so you need a lot of time. In order to improve the design quality and efficiency, affiliated with EXCEL VBA language developed &quot;composite material (Ver1.0) automatic typesetting system&quot;.\r\n', '../Public/uploads/2016-12-17/58555006f2fc2.png');
INSERT INTO `producten` VALUES ('22', 'MAIN SCREENSHOT', '', '../Public/uploads/2016-12-17/5855502ef1b37.png');
INSERT INTO `producten` VALUES ('23', 'MAIN SCREENSHOT', 'MAIN SCREENSHOTMAIN SCREENSHOTMAIN SCREENSHOTMAIN SCREENSHOTMAIN SCREENSHOTMAIN SCREENSHOTMAIN SCREENSHOTMAIN SCREENSHOTMAIN SCREENSHOTMAIN SCREENSHOTMAIN SCREENSHOTMAIN SCREENSHOTMAIN SCREENSHOTMAIN SCREENSHOTMAIN SCREENSHOTMAIN SCREENSHOTMAIN SCREENSHOTMAIN SCREENSHOTMAIN SCREENSHOTMAIN SCREENSHOTMAIN SCREENSHOTMAIN SCREENSHOTMAIN SCREENSHOTMAIN SCREENSHOTMAIN SCREENSHOTMAIN SCREENSHOTMAIN SCREENSHOTMAIN SCREENSHOTMAIN SCREENSHOTMAIN SCREENSHOTMAIN SCREENSHOTMAIN SCREENSHOTMAIN SCREENSHOTMAIN SCREENSHOTMAIN SCREENSHOTMAIN SCREENSHOT', '../Public/uploads/2016-12-17/5855504bb036c.png');
INSERT INTO `producten` VALUES ('26', 'PDMS DUCT RESISTANCE CALCULATION', 'PDMS DUCT RESISTANCE CALCULATIONPDMS DUCT RESISTANCE CALCULATIONPDMS DUCT RESISTANCE CALCULATIONPDMS DUCT RESISTANCE CALCULATIONPDMS DUCT RESISTANCE CALCULATIONPDMS DUCT RESISTANCE CALCULATIONPDMS DUCT RESISTANCE CALCULATIONPDMS DUCT RESISTANCE CALCULATIONPDMS DUCT RESISTANCE CALCULATIONPDMS DUCT RESISTANCE CALCULATIONPDMS DUCT RESISTANCE CALCULATIONPDMS DUCT RESISTANCE CALCULATIONPDMS DUCT RESISTANCE CALCULATION', '../Public/uploads/2016-12-17/5855524ecf638.png');
INSERT INTO `producten` VALUES ('27', 'The name of the software', 'PDMS', '../Public/uploads/2016-12-17/5855527d8595b.png');
INSERT INTO `producten` VALUES ('28', 'The software is introduced', 'The software based on BIM model off-line navigation platform development, the software in accordance with domestic design specifications calculation function; Cannot be based on the calculation of domestic existing software PDMS BIM software such as duct model to calculate; The existing calculation software without a perfect component parameter database', '../Public/uploads/2016-12-17/585552d1a2226.png');
INSERT INTO `producten` VALUES ('29', 'Software functions', '(1) frictional resistance calculation;\r\n(2) to calculate resistance; \r\n(3) the most unfavorable analysis;\r\n(4) the fan operating mode management and analysis;\r\n(5) the branch pipe resistance balance analysis, balancing valve open computing;\r\n(6) bureau of resistance type automatic matching components;\r\n(7)Generate calculation report.', '../Public/uploads/2016-12-17/585553294a27b.jpg');
INSERT INTO `producten` VALUES ('30', 'The software features', 'Comprehe', '../Public/uploads/2016-12-17/5855538e86a93.jpg');
INSERT INTO `producten` VALUES ('31', 'Normative', 'Normative', '../Public/uploads/2016-12-17/585553a59f357.jpg');
INSERT INTO `producten` VALUES ('32', 'Accuracy', 'Accuracy', '../Public/uploads/2016-12-17/585553bc54f0a.png');
INSERT INTO `producten` VALUES ('33', 'Simulation', 'Simulation', '../Public/uploads/2016-12-17/585553d130be9.png');
INSERT INTO `producten` VALUES ('34', 'Beautiful', 'Beautiful', '../Public/uploads/2016-12-17/585553e5d15cb.png');
INSERT INTO `producten` VALUES ('35', 'Profession', 'Profession', '../Public/uploads/2016-12-17/585553f9291f7.jpg');
INSERT INTO `producten` VALUES ('36', 'PROCESS DESIGN SOFTWARE', 'PROCESS DESIGN SOFTWAREPROCESS DESIGN SOFTWAREPROCESS DESIGN SOFTWARE', '../Public/uploads/2016-12-17/585554c168906.png');
INSERT INTO `producten` VALUES ('37', 'Absolute security of data', 'With existing data access, data access and data content filtering operation and so on the many kinds of access control mechanism, ensure the data security without blind Angle.', '../Public/uploads/2016-12-17/5855553991f1d.png');
INSERT INTO `producten` VALUES ('38', 'CADPS excellent network service performance', 'CADPS is introduced in the field of design for pipeline 2 d pipeline design and material management for the integration of comprehensive pipeline design system. CADPS by P&amp;ID BOM material statistics software, SPECEDIT PIPE grade design software four parts. As shown in the:', '../Public/uploads/2016-12-17/5855555b7d168.png');
INSERT INTO `producten` VALUES ('39', 'General introduction process software', 'A project from the process design, process piping to decorate material to the final statistics. Heavy drawing work and the process of the material statistics make engineers spend a lot of time and energy. In order to provide work efficiency, shorten the design cycle, CADPS series of 2 d pipeline design software, from the process design, piping design to material statistics provides you with all aspects of design tools.', '../Public/uploads/2016-12-17/58555589ac893.png');
INSERT INTO `producten` VALUES ('40', 'PIPE GALLERY OPERATION AND MAINTENANCE', 'PIPE GPIPE GALLERY OPERATION AND MAINTENANCEPIPE GALLERY OPERATION AND MAINTENANCEPIPE GALLERY OPERATION AND MAINTENANCEPIPE GALLERY OPERATION AND MAINTENANCEPIPE GALLERY OPERATION AND MAINTENANCEPIPE GALLERY OPERATION AND MAINTENANCEPIPE GALLERY OPERATION AND MAINTENANCEALLERY OPERATION AND MAINTENANCE', '../Public/uploads/2016-12-17/585556077fe21.jpg');
INSERT INTO `producten` VALUES ('41', 'comprehensive', 'supports win7 and 64bit systems', '../Public/uploads/2016-12-17/5855583d0adc1.jpg');
INSERT INTO `producten` VALUES ('42', 'comprehensive', 'provides commands applications', '../Public/uploads/2016-12-17/585558702374c.jpg');
INSERT INTO `producten` VALUES ('43', 'Fast, accurate and efficient gallery', 'Fast, accurate and efficient gallery', '../Public/uploads/2016-12-17/58555898b2089.jpg');
INSERT INTO `producten` VALUES ('44', 'operation', 'operation of underground gallery', '../Public/uploads/2016-12-17/585558d65cf0e.jpg');
INSERT INTO `producten` VALUES ('45', 'BIM', 'A three dimensional is built.', '../Public/uploads/2016-12-17/585558fb2a20f.jpg');
INSERT INTO `producten` VALUES ('46', 'GIS', 'Collection, storage, management, analysis and display of the geographical information of the integrated pipe management.', '../Public/uploads/2016-12-17/5855592f1cd5d.jpg');
INSERT INTO `producten` VALUES ('47', 'Peration and maintenance', 'The use of GIS technology and BIM technology, combined with the development of,the effective implementation of the comprehensive pipe gallery digital standard operation and maintenance management', '../Public/uploads/2016-12-17/585559544b013.jpg');
INSERT INTO `producten` VALUES ('48', 'WISDOM PIPE GALLERY', 'WISDOM PIPE GALLERYWISDOM PIPE GALLERYWISDOM PIPE GALLERYWISDOM PIPE GALLERYWISDOM PIPE GALLERY', '../Public/uploads/2016-12-17/585559c91fe10.png');
INSERT INTO `producten` VALUES ('49', 'General introduction:', 'Shanghua software for informatization construction based on the field, focus on promoting the city comprehensive pipe gallery (&quot;common ditch&quot;) construction, for the construction of the underground pipe gallery planning and design complex, difficult construction, operation management and maintenance of large amount of information and other difficulties, combined with MCC Beijing, Chinese Municipal Institute of North China, combined with the status quo of domestic design construction and maintenance, foreign experience, through the design and operation management to realize the underground pipe gallery software technology.', '../Public/uploads/2016-12-17/58555e586ca20.png');
INSERT INTO `producten` VALUES ('50', 'Function features:', 'Scheme and construction design of comprehensive pipe gallery project; design of water, rainwater, sewage and reclaimed water, gas, heat, electricity, communications and other projects in the pipeline pipe gallery; rainwater, sewage inlet design, longitudinal section; comprehensive pipe gallery rainwater pipeline design; sewage pipe pipe corridor laying design.', '../Public/uploads/2016-12-17/58555a99f3677.jpg');
INSERT INTO `producten` VALUES ('51', 'Technical features:', 'Shanghua software based on the engineering construction of information field, focus on promoting the construction of city underground pipe gallery (underground &quot;highway&quot;), for the construction of the underground pipe gallery planning and design complex, difficult construction, operation management and maintenance of large amount of information and other difficulties, combined with the status quo in the design, construction, operation and maintenance, learn from foreign experience. The design and implementation of underground pipe gallery of software technology, improve the design efficiency, convenient operation and maintenance.', '../Public/uploads/2016-12-17/58555b05e8c21.jpg');
INSERT INTO `producten` VALUES ('52', 'Product features:', 'Scheme and construction design of comprehensive pipe gallery project; design of water, rainwater, sewage and reclaimed water, gas, heat, electricity, communications and other projects in the pipeline pipe gallery; rainwater, sewage inlet design, longitudinal section; comprehensive pipe gallery rainwater pipeline design; sewage pipe pipe corridor laying design;', '../Public/uploads/2016-12-17/58555b24c32c9.png');
INSERT INTO `producten` VALUES ('53', 'Design features', 'Shanghua software based on the engineering construction of information field, focus on promoting the construction of city underground pipe gallery (underground &quot;highway&quot;), for the construction of the underground pipe gallery planning and design complex, difficult construction, operation management and maintenance of large amount of information and other difficulties, combined with the status quo in the design, construction, operation and maintenance, learn from foreign experience. The design and implementation of underground pipe gallery', '../Public/uploads/2016-12-17/58555ed389dc4.jpg');
INSERT INTO `producten` VALUES ('55', 'Composite pipe rack design software', '', '../Public/uploads/2016-12-19/58578694eb1b1.jpg');
INSERT INTO `producten` VALUES ('56', 'Comprehensive utility tunnel operational system', '', '../Public/uploads/2016-12-19/585786b0e7f59.jpg');
INSERT INTO `producten` VALUES ('57', 'Green construction simulation analysis', '', '../Public/uploads/2016-12-19/585786cc6c82e.jpg');
INSERT INTO `producten` VALUES ('58', 'Design assistant DWGHelp', '', '../Public/uploads/2016-12-19/5857872cafab7.jpg');
INSERT INTO `producten` VALUES ('59', 'PDMS duct hydraulic calculation&lt;', '', '../Public/uploads/2016-12-19/58578781e39cf.jpg');
INSERT INTO `producten` VALUES ('61', 'PDMS composite material automatic typesetting system', '', '../Public/uploads/2016-12-19/585788319c26a.jpg');
INSERT INTO `producten` VALUES ('62', 'Process design software', '', '../Public/uploads/2016-12-19/585787b4279c3.jpg');
INSERT INTO `producten` VALUES ('63', 'Pipe rack', '', '../Public/uploads/2016-12-19/585787c88e3ef.jpg');
INSERT INTO `producten` VALUES ('64', 'VE', '', '../Public/uploads/2016-12-19/585787e04dc8b.jpg');
